#hellomake: hellomake.c hellofunc.c
	#gcc -o hellomake hellomake.c hellofunc.c -I.
CC=g++
all:
	#$(CC) sdl_display.c -o app -I/home/ejoy/Downloads/SDL2-2.0.14/_install/include -I/home/ejoy/Downloads/SDL2-2.0.14/_install/include/SDL2 -lSDL2 -L/home/ejoy/Downloads/SDL2-2.0.14/_install/lib -lpthread -lm -ldl -std=gnu++0x -l/home/ejoy/Downloads/SDL2-2.0.14/_install/lib/libSDL2-2.0.so.0
	$(CC) sdl_display.cpp -o app -I/home/ejoy/Downloads/SDL2-2.0.14/_install/include -I/home/ejoy/Downloads/SDL2-2.0.14/_install/include/SDL2 -lSDL2 -L/home/ejoy/Downloads/SDL2-2.0.14/_install/lib -lpthread -lm -ldl -std=gnu++0x
	#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ejoy/Downloads/SDL2-2.0.14/_install/lib
